# Generated by Django 4.2.7 on 2025-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnaseq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='expression_matrix',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='rnaseq/matrices/'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='expression_matrix_output',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='rnaseq/output_matrices/'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='metadata_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='rnaseq/metadata/'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='qc_report',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='rnaseq/qc/'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='results_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='rnaseq/results/'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='visualization_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='rnaseq/visualizations/'),
        ),
    ]
