# Generated by Django 4.2.7 on 2025-08-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnaseq', '0002_add_job_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnaseqdataset',
            name='fastq_files',
            field=models.JSONField(default=list, help_text='Multiple FASTQ file paths for multi-sample analysis'),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='sample_files_mapping',
            field=models.JSONField(default=dict, help_text='Mapping of sample IDs to FASTQ file paths'),
        ),
    ]
