# Generated by Django 4.2.7 on 2025-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnaseq', '0003_rnaseqdataset_fastq_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='fastq_files',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='sample_files_mapping',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='sample_sheet',
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='analysis_type',
            field=models.CharField(choices=[('bulk_rnaseq', 'Bulk RNA-seq Pipeline'), ('bulk_comprehensive', 'Bulk Comprehensive Analysis'), ('scrna_rnaseq', 'Single-cell RNA-seq Pipeline'), ('scrna_comprehensive', 'Single-cell Comprehensive Analysis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rnaseqdataset',
            name='analysis_type',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive Analysis')], default='comprehensive', max_length=50),
        ),
    ]
