# Generated by Django 4.2.7 on 2025-08-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnaseq', '0004_remove_rnaseqdataset_fastq_files_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnaseqpresentation',
            options={},
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='current_user_input',
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='enable_ai_interpretation',
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='result_files',
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='sample_files',
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='sample_metadata',
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='user_hypothesis',
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='waiting_for_input',
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='ai_interpretation',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='alignment_bam',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='counts_file',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='expression_matrix_counts',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='expression_matrix_tpm',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='fastq_r1_file',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='fastq_r2_file',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='gene_signatures',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='generated_metadata',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='phenotype_data',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='quality_thresholds',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='results_file',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='start_from_upstream',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='trimmed_fastq_r1',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='trimmed_fastq_r2',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='user_hypothesis',
        ),
        migrations.RemoveField(
            model_name='rnaseqdataset',
            name='visualization_image',
        ),
        migrations.RemoveField(
            model_name='rnaseqpresentation',
            name='slide_order',
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='processing_metrics',
            field=models.JSONField(default=dict, help_text='Processing metrics and statistics'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='total_steps',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='ai_chat_history',
            field=models.JSONField(default=list, help_text='AI chatbot conversation history'),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='alignment_stats',
            field=models.JSONField(default=dict, help_text='Alignment statistics'),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='analysis_plots',
            field=models.JSONField(default=list, help_text='Generated visualization plots'),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='downstream_results',
            field=models.JSONField(default=dict, help_text='Downstream analysis results'),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='expression_matrix',
            field=models.FileField(blank=True, null=True, upload_to='rnaseq/matrices/'),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='expression_matrix_output',
            field=models.FileField(blank=True, null=True, upload_to='rnaseq/output_matrices/'),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='fastq_files',
            field=models.JSONField(default=list, help_text='List of FASTQ file pairs'),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='sample_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='selected_pipeline_stage',
            field=models.CharField(choices=[('upstream', 'Upstream Processing'), ('downstream', 'Downstream Analysis')], default='upstream', max_length=20),
        ),
        migrations.AddField(
            model_name='rnaseqdataset',
            name='upstream_results',
            field=models.JSONField(default=dict, help_text='Upstream processing results'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='analysis_type',
            field=models.CharField(choices=[('bulk_upstream', 'Bulk RNA-seq Upstream'), ('bulk_downstream', 'Bulk RNA-seq Downstream'), ('scrna_upstream', 'Single-cell RNA-seq Upstream'), ('scrna_downstream', 'Single-cell RNA-seq Downstream')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rnaseqdataset',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing_upstream', 'Processing Upstream'), ('upstream_complete', 'Upstream Complete'), ('processing_downstream', 'Processing Downstream'), ('completed', 'Analysis Complete'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='rnaseqpathwayresult',
            name='database',
            field=models.CharField(choices=[('GO', 'Gene Ontology'), ('KEGG', 'KEGG'), ('REACTOME', 'Reactome'), ('HALLMARK', 'MSigDB Hallmark')], max_length=50),
        ),
        migrations.CreateModel(
            name='RNASeqAIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('context_data', models.JSONField(default=dict, help_text='Analysis context for AI response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to='rnaseq.rnaseqdataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
