# Generated by Django 4.2.7 on 2025-08-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnaseq', '0005_alter_rnaseqpresentation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='current_user_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='enable_ai_interpretation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='result_files',
            field=models.JSONField(default=list, help_text='List of generated result files'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='user_hypothesis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='waiting_for_input',
            field=models.BooleanField(default=False),
        ),
    ]
