# Generated by Django 5.1.5 on 2025-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_slide_rendered_image_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='base_price',
            field=models.PositiveIntegerField(default=0, help_text='Base price in cents before discount'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Actual payment in cents after discount'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='credits_added',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
