# Generated by Django 5.1.5 on 2025-06-12 07:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersubscription_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive for recharges, negative for usage', max_digits=8),
        ),
    ]
