# Generated by Django 5.1.5 on 2025-06-12 07:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_credittransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="User's available credits (supports fractional values)", max_digits=8),
        ),
    ]
