# Generated by Django 5.1.5 on 2025-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateimage',
            name='type',
            field=models.CharField(choices=[('2d', '2D'), ('3d', '3D')], default='2d', max_length=2),
        ),
    ]
