# Generated by Django 5.1.5 on 2025-06-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_templateimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='exported_file',
            field=models.FileField(blank=True, null=True, upload_to='exports/'),
        ),
    ]
