# Generated by Django 5.1.5 on 2025-06-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_presentation_exported_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='export_format',
            field=models.CharField(blank=True, choices=[('pptx', 'PowerPoint'), ('pdf', 'PDF'), ('mp4', 'Video')], max_length=10),
        ),
    ]
