# Generated by Django 4.2.7 on 2025-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_enhanced_presentation_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='presentation_type',
            field=models.CharField(choices=[('slides', 'Slide Presentation'), ('document', 'Rich Document')], default='slides', max_length=20),
        ),
        migrations.AlterField(
            model_name='slide',
            name='rich_content',
            field=models.TextField(blank=True, help_text='Rich HTML content for document sections'),
        ),
    ]
